name: "Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version (without v)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
          always-auth: true
          registry-url: "https://registry.npmjs.org"

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
      - run: yarn version --new-version ${{ github.event.inputs.version }} --no-commit-hooks
      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}

      - name: Publushing release
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
